### ISSUE TITLE
[BUG] West Nile - unaligned sequences not loading

### ISSUE THREAD

**Issue by anna-parker** [pathoplexus/pathoplexus#240]
**Describe the bug**
On pathoplexus.org all west nile unaligned sequences are not loading in the preview or respective details pages
https://files.slack.com/files-pri/T05FDTF8TN0-F07S2QGQ55X/image.png

The exact error message is: 
```
Failed to load nucleotide sequence main: {"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n at Mr (https://pathoplexus.org/_astro/createAuthorizationHeader.YJf_AUYe.js:3:1027)\n at XMLHttpRequest.C (https://pathoplexus.org/_astro/createAuthorizationHeader.YJf_AUYe.js:3:6042)\n at ce.request (https://pathoplexus.org/_astro/createAuthorizationHeader.YJf_AUYe.js:5:1953)\n at async _a.request (https://pathoplexus.org/_astro/createAuthorizationHeader.YJf_AUYe.js:11:4348)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"baseURL":"https://lapis.pathoplexus.org/west-nile","method":"post","url":"/sample/unalignedNucleotideSequences","data":"{\"accessionVersion\":\"PP_0004H7V.2\"}","params":{}},"code":"ERR_BAD_RESPONSE","status":500}
```
In the LAPIS/SILO logs I see: 

```
[2024-10-14 07:29:48.954] [logger] [info] [query_handler.cpp:33] Request Id [47e78b35-045a-41aa-be09-59977b51b3ea] - received query: {"action":{"randomize":false,"type":"Fasta","sequenceName":"main"},"filterExpression":{"children":[{"children":[{"column":"accessionVersion","value":"PP_0004H7V.2","type":"StringEquals"}],"type":"Or"}],"type":"And"}}
[2024-10-14 07:29:48.960] [logger] [error] [error_request_handler.cpp:45] Caught exception: IO Error: No files found that match the pattern "/data/1728407340/unaligned_nuc_0/*/*.parquet"
[2024-10-14 07:29:48.960] [logger] [info] [logging_request_handler.cpp:21] Request Id [47e78b35-045a-41aa-be09-59977b51b3ea] - Responding with status code 500
```

**Comment by theosanderson** [comment]
I don't really remember about this issue - can we close it?
